EXP_NAME: 'behave_test'
PROJECT_NAME: 'DECO_BEHAVE_Testing'
OUTPUT_DIR: 'deco_results'
CONDOR_DIR: ''
DATASET:
  BATCH_SIZE: 8
  NUM_WORKERS: 4
  NORMALIZE_IMAGES: [True]
OPTIMIZER:
  TYPE: 'adam'
  LR: [1e-5]
  NUM_UPDATE_LR: 3
TRAINING:
  ENCODER: 'sam_hrnet'
  CONTEXT: [True]
  NUM_EPOCHS: 60
  NUM_EARLY_STOP: 10
  SUMMARY_STEPS: 5
  CHECKPOINT_EPOCHS: 5
  DATASETS: ['damon']
  DATASET_MIX_PDF: ['1.0']
  DATASET_ROOT_PATH: ''
  BEST_MODEL_PATH: './checkpoints/ours.pth'  # demo_train_best.pth
  LOSS_WEIGHTS: 1.
  PAL_LOSS_WEIGHTS: 0.0
  DISTILL: False
  DISTILL_DINO_WEIGHT: 0.04
  DISTILL_OUT_WEIGHT: 1.0
  DISTILL_RAMP_STEPS: 4000
VALIDATION:
  SUMMARY_STEPS: 10000
  DATASETS: ['behave']
  MAIN_DATASET: 'behave'
TEST_TIME:
  ENABLED: False
  STEPS: 2
  LR: 1.e-5
  ZOOM_SCALES: [1.25, 1.5]
  CONSISTENCY_WEIGHT: 1.0
  ENSEMBLE_ORIGINAL_WEIGHT: 1.0
  ORIGINAL_ANCHOR_WEIGHT: 1.0
  HIGHRES_ZOOM_ENABLED: True
  HIGHRES_SIZE: 512
  MIN_KEYPOINT_RETENTION: 0.8
  MIN_OBJECT_RETENTION: 0.8
  CONTACT_THRESHOLD: 0.5
  EMA_MOMENTUM: 0.996
  FOCUS_PROMPTS: True
