EXP_NAME: 'damon_hrnet_testing'
PROJECT_NAME: 'DECO_DAMON_Testing'
OUTPUT_DIR: 'deco_results'
CONDOR_DIR: ''
DATASET:
  BATCH_SIZE: 1
  NUM_WORKERS: 4
  NORMALIZE_IMAGES: [True]
OPTIMIZER:
  TYPE: 'adam'
  LR: [5e-5]
  NUM_UPDATE_LR: 3
TRAINING:
  ENCODER: 'sam_sam'    # 'hrnet'
  CONTEXT: [True]
  NUM_EPOCHS: 1
  NUM_EARLY_STOP: 10
  SUMMARY_STEPS: 5
  CHECKPOINT_EPOCHS: 5
  DATASETS: ['damon']
  DATASET_MIX_PDF: ['1.']
  DATASET_ROOT_PATH: '/home/l_z80934/scratch/deco'    # ''
  BEST_MODEL_PATH: './checkpoints/demo_train_best.pth'  # './checkpoints/Release_Checkpoint/deco_best.pth'
  PAL_LOSS_WEIGHTS: 0.0
VALIDATION:
  SUMMARY_STEPS: 1000
  DATASETS: ['damon']
  MAIN_DATASET: 'damon'
TEST_TIME:
  ENABLED: False
  STEPS: 0 # 2, 0, 2, 4
  LR: 1.e-6  # 2.e-5
  ZOOM_SCALES:  [1.125] # [1.05, 1.125], [1.125, 1.25], [1.25, 1.5]
  CONSISTENCY_WEIGHT: 1.0
  ENSEMBLE_ORIGINAL_WEIGHT: 3.0  # 1.0, 2.0
  EMA_MOMENTUM: 0.996
  FOCUS_PROMPTS: True
